### ISSUE TITLE
media_player.power_off toggles power state regardless of what state the device is in

### ISSUE THREAD

**Issue by mrdarrengriffin** [4n0nD3v3l0p3r/Home_Assistant_SkyQ_MediaPlayer#9]
Will follow with PR

**Comment by bangcrash** [comment]
Any news on a fix for this please?  I've got this problem as well.

Thanks

**Comment by mrdarrengriffin** [comment]
You can see my pull request here:
https://github.com/4n0nD3v3l0p3r/Home_Assistant_SkyQ_MediaPlayer/pull/10

**Comment by mrdarrengriffin** [comment]
Feel free to make the changes yourself, or use my forked repo: https://github.com/mrdarrengriffin/Home_Assistant_SkyQ_MediaPlayer

However my repo won't be maintained.

**Comment by MadmanMonty** [comment]
Merged #10 to fix this issue.

Recent maintained instance of this code can be found here https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer and may be worth exploring
